## IMDb Movie Metadata Collection

In [1]:
# Intialization
import os
import time

import warnings
warnings.filterwarnings("ignore")

# data science imports
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# Use the OMDb API to collect more movie information
import requests
from bs4 import BeautifulSoup
# import ast
# import unicodedata

In [2]:
# Set Locations
data_path = 'C:/Users/IOLAP-USER/Documents/Movie-Recommendation-System/Data/Reviews-1M/'

#### Import and collect movies data
This includes the movieId, title, and genres provided in the Movie Lens data.

In [3]:
# movies_df = pd.read_csv(data_path + 'movies.dat', 
#                         sep = '::', header=None)
# movies_df.columns = ['itemId', 'title', 'genres']
# movies_df['genres'] = movies_df.genres.apply(lambda x: x.split('|'))
# movies_df.head()

In [4]:
# def movie_metadata_extract(title_val):
#     time.sleep(2)
#     # remove the year from the title
#     title = title_val[0:-7]
#     title = title.split(' (')[0]
#     if title[-5:] == ', The':
#         title = 'The ' + title[0:-5]
#     elif title[-4:] == ', An':
#         title = 'An ' + title[0:-4]
#     elif title[-4:] == ', La':
#         title = 'La ' + title[0:-4]
#     elif title[-3:] == ', A':
#         title = 'A ' + title[0:-3]

#     year = title_val[-5:-1]

#     movie_request = requests.get('http://www.omdbapi.com/?apikey=7813f0a5&', 
#                                  {'t': title, 'y': year})
#     movie_dict = movie_request.json()
#     if movie_dict.get('Response') == 'True':
#         imdb_rating = [0 if movie_dict.get('imdbRating') == 'N/A' 
#                        else float(movie_dict.get('imdbRating'))][0]

#         imdb_votes = [0 if movie_dict.get('imdbVotes') == 'N/A' 
#                      else int(movie_dict.get('imdbVotes').replace(',', ''))][0]

#         metascore = [0 if movie_dict.get('Metascore') == 'N/A' 
#                      else int(movie_dict.get('Metascore'))][0]

#         runtime = [0 if movie_dict.get('Runtime') == 'N/A' 
#                      else int(movie_dict.get('Runtime')[0:-4])][0] 
        
#         genre_list = [g.encode('ascii', 'ignore').decode('utf-8') for g in movie_dict.get('Genre').split(', ')]

#         director_list = [d.encode('ascii', 'ignore').decode('utf-8') for d in movie_dict.get('Director').split(', ')]

#         director_list = [director.split('(')[0] for director in director_list]

#         actor_list = [a.encode('ascii', 'ignore').decode('utf-8') for a in movie_dict.get('Actors').split(', ')]
#         actor_list = [actor.split('(')[0] for actor in actor_list]

#         return(pd.Series([movie_dict.get('imdbID'), 
#                           imdb_rating,
#                           imdb_votes,
#                           metascore,
#                           runtime,
#                           movie_dict.get('Rated'), 
#                           genre_list,
#                           director_list,
#                           actor_list],
#                          index=['imdb_id', 
#                                 'imdb_rating', 'imdb_votes', 
#                                 'metascore', 'runtime', 
#                                 'MPAA_rating', 'imdb_genres', 
#                                 'director', 'actors']))
#     else:
#         text = title + ' ' + year + ' movie'
#         text = text.replace(' ', '%20')

#         response = requests.get('https://google.com/search?q=' + text)

#         imdbID = ''
#         soup = BeautifulSoup(response.text)
#         for a in soup.find_all('a'):
#               if a.get('href')[0:34] == '/url?q=https://www.imdb.com/title/':
#                 imdbID = a.get('href')[32:45].split('/')[1]
#                 break
                
#         movie_request = requests.get('http://www.omdbapi.com/?apikey=7813f0a5&', 
#                                      {'i': imdbID})
#         movie_dict = movie_request.json()
#         if movie_dict.get('Response') == 'True':
#             imdb_rating = [0 if movie_dict.get('imdbRating') == 'N/A' 
#                            else float(movie_dict.get('imdbRating'))][0]

#             imdb_votes = [0 if movie_dict.get('imdbVotes') == 'N/A' 
#                          else int(movie_dict.get('imdbVotes').replace(',', ''))][0]

#             metascore = [0 if movie_dict.get('Metascore') == 'N/A' 
#                          else int(movie_dict.get('Metascore'))][0]

#             runtime = [0 if movie_dict.get('Runtime') == 'N/A' 
#                          else int(movie_dict.get('Runtime')[0:-4])][0] 
            
#             genre_list = [g.encode('ascii', 'ignore').decode('utf-8') for g in movie_dict.get('Genre').split(', ')]

#             director_list = [d.encode('ascii', 'ignore').decode('utf-8') for d in movie_dict.get('Director').split(', ')]

#             director_list = [director.split('(')[0] for director in director_list]

#             actor_list = [a.encode('ascii', 'ignore').decode('utf-8') for a in movie_dict.get('Actors').split(', ')]
#             actor_list = [actor.split('(')[0] for actor in actor_list]

#             return(pd.Series([movie_dict.get('imdbID'), 
#                               imdb_rating,
#                               imdb_votes,
#                               metascore,
#                               runtime,
#                               movie_dict.get('Rated'), 
#                               genre_list,
#                               director_list,
#                               actor_list],
#                              index=['imdb_id', 
#                                     'imdb_rating', 'imdb_votes', 
#                                     'metascore', 'runtime', 
#                                     'MPAA_rating', 'imdb_genres', 
#                                     'director', 'actors']))
        
        
#         else:
#             print(movie_dict.get('Error') + ' ' + title)
#             return(pd.Series(['', 
#                               0, 0, 0, 0,
#                               '', [''], [''], ['']],
#                              index=['imdb_id', 
#                                     'imdb_rating', 'imdb_votes', 
#                                     'metascore', 'runtime', 
#                                     'MPAA_rating', 'imdb_genres', 
#                                     'director', 'actors']))

In [5]:
# # Collect metadata
# movies_df_2 = pd.concat([movies_df, 
#                          movies_df.title.apply(movie_metadata_extract)],
#                         axis = 1)
# # separate the year from the title
# movies_df_2['year'] = [y[-5:-1] for y in movies_df_2.title]
# # remove the year from the title
# movies_df_2['title'] = [t[:-7] for t in movies_df_2.title]

# movies_df_2.head(2)

In [6]:
# Only needed if movies_metadata had already been created
movies_df_2 = pd.read_csv(data_path + 'movies_metadata.csv')
movies_df_2['director'] = movies_df_2.director.apply(lambda x: str(x).replace('_', ' ').split(', '))
movies_df_2['actors'] = movies_df_2.actors.apply(lambda x: str(x).replace('_', ' ').split(', '))
movies_df_2['genres'] = movies_df_2.genres.apply(lambda x: str(x).split(', '))
movies_df_2['imdb_genres'] = movies_df_2.imdb_genres.apply(lambda x: str(x).split(', '))
movies_df_2.head()

,itemId,title,genres,imdb_id,imdb_rating,imdb_votes,metascore,runtime,MPAA_rating,imdb_genres,director,actors,year
0,3699,Starman,"[Adventure, Drama, Romance, Sci-Fi]",tt0088172,7.0,38393,71,115,PG,"[Romance, Sci-Fi]",[John Carpenter],"[Jeff Bridges, Karen Allen, Charles Martin Smi...",1984
1,3700,"Brother from Another Planet, The","[Drama, Sci-Fi]",tt0087004,6.8,5050,0,108,R,"[Comedy, Sci-Fi]",[John Sayles],"[Joe Morton, Rosanna Carter, Ray Ramirez, Yves...",1984
2,3701,Alien Nation,"[Crime, Drama, Sci-Fi]",tt0094631,6.3,12867,45,91,R,"[Action, Sci-Fi]",[Graham Baker],"[James Caan, Mandy Patinkin, Terence Stamp, Ke...",1988
3,3702,Mad Max,"[Action, Sci-Fi]",tt0079501,7.0,173984,73,88,R,"[Action, Adventure, Sci-Fi, Thriller]",[George Miller],"[Mel Gibson, Joanne Samuel, Hugh KeaysByrne, S...",1979
4,3703,Mad Max 2 (a.k.a. The Road Warrior),"[Action, Sci-Fi]",tt0082694,7.6,152866,77,94,R,"[Action, Adventure, Sci-Fi, Thriller]",[George Miller],"[Mel Gibson, Bruce Spence, Michael Preston, Ma...",1981

In [7]:
# one hot encode the genres using the sklearn MultiLabelBinarizer
# this works better than pandas get_dummies because it can handle multiple class inputs as lists
mlb_movie_lens_genres = MultiLabelBinarizer()
movies_df_3 = movies_df_2.join(pd.DataFrame(mlb_movie_lens_genres.fit_transform(movies_df_2.genres),
                                            columns = mlb_movie_lens_genres.classes_,
                                            index = movies_df_2.index).add_prefix('ml_genre_'))

In [8]:
mlb_imdb_genres = MultiLabelBinarizer()
movies_df_3 = movies_df_3.join(pd.DataFrame(mlb_imdb_genres.fit_transform(movies_df_3.imdb_genres),
                                            columns = mlb_imdb_genres.classes_,
                                            index = movies_df_3.index).add_prefix('imdb_genre_'))

In [9]:
mlb_imdb_director = MultiLabelBinarizer()
movies_df_3 = movies_df_3.join(pd.DataFrame(mlb_imdb_director.fit_transform(movies_df_3.director),
                                            columns = mlb_imdb_director.classes_,
                                            index = movies_df_3.index).add_prefix('director_'))

In [10]:
mlb_imdb_actors = MultiLabelBinarizer()
movies_df_3 = movies_df_3.join(pd.DataFrame(mlb_imdb_actors.fit_transform(movies_df_3.actors),
                                            columns = mlb_imdb_actors.classes_,
                                            index = movies_df_3.index).add_prefix('actor_'))

In [11]:
ohe_mpaa_ratings = pd.get_dummies(movies_df_3.MPAA_rating, prefix = 'MPAA_rating')
movies_df_3 = pd.concat([movies_df_3, ohe_mpaa_ratings], axis = 1, sort = False)
movies_df_3.drop(['genres', 'imdb_genres', 'director', 'actors', 'MPAA_rating'], axis = 1, inplace = True)
movies_df_3.columns = [c.replace(' ', '_') for c in movies_df_3.columns]
movies_df_3.columns = [c.replace('/', '') for c in movies_df_3.columns]
movies_df_3.columns = [c.replace('.', '') for c in movies_df_3.columns]
movies_df_3.columns = [c.replace('-', '') for c in movies_df_3.columns]
movies_df_3.columns = [c.replace("'", '') for c in movies_df_3.columns]
movies_df_3.title = [t.encode('ascii', 'ignore').decode('utf-8')
                     for t in movies_df_3.title]
movies_df_3.head()

,itemId,title,imdb_id,imdb_rating,imdb_votes,metascore,runtime,year,ml_genre_Action,ml_genre_Adventure,...,MPAA_rating_PG13,MPAA_rating_Passed,MPAA_rating_R,MPAA_rating_TV14,MPAA_rating_TVG,MPAA_rating_TVMA,MPAA_rating_TVPG,MPAA_rating_UNRATED,MPAA_rating_Unrated,MPAA_rating_X
0,3699,Starman,tt0088172,7.0,38393,71,115,1984,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3700,"Brother from Another Planet, The",tt0087004,6.8,5050,0,108,1984,0,0,...,0,0,1,0,0,0,0,0,0,0
2,3701,Alien Nation,tt0094631,6.3,12867,45,91,1988,0,0,...,0,0,1,0,0,0,0,0,0,0
3,3702,Mad Max,tt0079501,7.0,173984,73,88,1979,1,0,...,0,0,1,0,0,0,0,0,0,0
4,3703,Mad Max 2 (a.k.a. The Road Warrior),tt0082694,7.6,152866,77,94,1981,1,0,...,0,0,1,0,0,0,0,0,0,0

In [12]:
# movies_df_2.genres = movies_df_2.genres.apply(', '.join)
# movies_df_2.imdb_genres = movies_df_2.imdb_genres.apply(', '.join)
# movies_df_2.director = movies_df_2.director.apply(', '.join)
# movies_df_2.actors = movies_df_2.actors.apply(', '.join)
# movies_df_2.head(2)

In [13]:
# # Write movies with metadata to file
# movies_df_2.to_csv(data_path + 'movies_metadata.csv', index = False)

In [14]:
movies_df_3['itemId'] = movies_df_3.itemId.astype(int)
movies_df_3['title'] = movies_df_3.title.astype(str)
movies_df_3['imdb_id'] = movies_df_3.imdb_id.astype(str)
movies_df_3['imdb_rating'] = movies_df_3.imdb_rating.astype(float)
movies_df_3.iloc[:, 4:] = movies_df_3.iloc[:, 4:].astype(int)
# Combine MPAA NOT RATED, Not Rated, Unrated, and UNRATED
movies_df_3['MPAA_rating_Unrated'] = movies_df_3[[
    'MPAA_rating_Unrated', 'MPAA_rating_UNRATED', 'MPAA_rating_NOT_RATED', 
    'MPAA_rating_Not_Rated']].apply(sum, axis = 1)
# Combine APPROVED, Approved, blank, NA, Passed, PASSED
movies_df_3['MPAA_rating_Other'] = movies_df_3[[
    'MPAA_rating_APPROVED', 'MPAA_rating_Approved', # 'MPAA_rating_', 'MPAA_rating_NA', 
    'MPAA_rating_Passed', 'MPAA_rating_PASSED']].apply(sum, axis = 1)
# Combine M, GP, MPG, and PG - These are all the same, just a how the ratings evolved
movies_df_3['MPAA_rating_PG'] = movies_df_3[[
    'MPAA_rating_PG', 'MPAA_rating_GP', 'MPAA_rating_M', 
    'MPAA_rating_MPG']].apply(sum, axis = 1)
# Drop now unnecessary columns
movies_df_3.drop(['MPAA_rating_UNRATED', 'MPAA_rating_NOT_RATED', 'MPAA_rating_APPROVED', 
                  'MPAA_rating_Approved', # 'MPAA_rating_', 'MPAA_rating_NA', 
                  'MPAA_rating_Passed', 'MPAA_rating_PASSED', 'MPAA_rating_Not_Rated', 
                  'MPAA_rating_GP', 'MPAA_rating_M', 'MPAA_rating_MPG'], axis = 1, inplace = True)

In [15]:
# write movies metadata binarized to file
movies_df_3.to_csv(data_path + 'movies_metadata_ohe.csv', index = False)